# Generated by Django 2.1.5 on 2020-01-31 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='NE', max_length=50)),
                ('zipcode', models.CharField(default='00000', max_length=10)),
                ('email', models.EmailField(default=' ', max_length=100)),
                ('cell_phone', models.CharField(default='(402)000-0000', max_length=50)),
                ('acct_number', models.CharField(blank=True, default='00000', max_length=50, null=True)),
                ('notes', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=140)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Vechicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodel', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('VINnumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('PurchaseDate', models.DateTimeField(blank=True, default='', null=True)),
                ('LastServiceDate', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='vechicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Vechicle'),
        ),
    ]
