# Generated by Django 2.1.5 on 2020-01-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='vechicle',
        ),
        migrations.AddField(
            model_name='vechicle',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
